### ISSUE TITLE
toHex

### ISSUE THREAD

**Issue by strarsis** [ssnepenthe/color-utils#11]
Is there a `toHex` function for getting the printable hex value of a color (optionally with or without '#')?

**Comment by ssnepenthe** [comment]
There are no dedicated hex helper functions, but the following methods are available on color objects via the underlying rgb objects:

```php
color('red')->toHexArray(); // ['red' => 'ff', 'green' => '00', 'blue' => '00']
color('red')->toHexString(); // '#ff0000'
```

Additionally, there are getters for each channel:

```php
color('red')->getRedByte(); // 'ff'
color('red')->getGreenByte(); // '00'
color('red')->getBlueByte(); // '00'
```

Hope it helps.

**Comment by strarsis** [comment]
`toHexString()` does what I am looking for.
