### ISSUE TITLE
PHP Parse error syntax error, unexpected ':', expecting '{'

### ISSUE THREAD

**Issue by chadcrowell** [ssnepenthe/color-utils#15]
Your library is composer installed as a dependency for my Craft CMS site. I run many Craft sites and am getting this error when running composer update on many of them. PHP 7.2.11

PHP Parse error:  syntax error, unexpected ':', expecting '{' in /home/path/vendor/ssnepenthe/color-utils/inc/colors.php on line 9

**Comment by ssnepenthe** [comment]
Thanks for the report.

That looks like a parse error related to the use of return type declarations and would be expected on any version of PHP below 7.0.

Is it possible that some of your sites are on an older version of PHP or have multiple versions installed?

Can you run `composer diagnose` on one of the failing sites and let me know what it shows for the PHP version?

edited: update command from about to diagnose

**Comment by chadcrowell** [comment]
Here is the composer output:
Running 1.8.5 (2019-04-09 17:46:47) with PHP 5.6.36 on Linux / 3.14.52-vs2.3.6.15-1

I was able to change my server's default PHP version to 7.2 and that appears to have taken care of the reported issue. Thanks for the direction.

**Comment by aditya-tribes** [comment]
![image](https://user-images.githubusercontent.com/113181879/189942504-6c3cba75-2c17-4cad-abf4-8e9701a84d03.png)
when clone craft cms project my localhost ( clone file import database , set .env file ) but display this type error

**Comment by aditya-tribes** [comment]
.env file 
![image](https://user-images.githubusercontent.com/113181879/189943110-53973944-931f-451f-ba7d-a4827cdc63a9.png)

**Comment by ssnepenthe** [comment]
I don't see anything in that trace related to this package (color-utils)...

That said - what version of php are you running? A parse error related to the '|' character screams unions types which requires php 8.0 or higher.
